### ISSUE TITLE
Why sort RMI methods?

### ISSUE THREAD

**Issue by guangmuzhu** [delphix/dsp#1]
Hi,

Class RmiMethodOrdering used in method createProxy of class RmiFactoryImpl. I could see the need to map the method name to the Method instance, but cannot understand the reason for sorting the method names as well as why use a hashMap for index and a List for instance. Could somebody tell me why?

Best wishes
Guangmu Zhu

```java
    private List<Method> methods = Lists.newArrayList();
    private Map<Method, Integer> placement = Maps.newHashMap();

    public RmiMethodOrdering(Class<?> clazz) {
        Map<String, Method> methodMap = Maps.newHashMap();
        for (Method m : clazz.getMethods()) {
            List<String> paramNames = Lists.newArrayList();
            for (Class<?> paramType : m.getParameterTypes()) {
                paramNames.add(paramType.getCanonicalName());
            }
            String str = String.format("%s(%s)", m.getName(), StringUtils.join(paramNames, ", "));
            methodMap.put(str, m);
        }

        List<String> sortedNames = new ArrayList<String>(methodMap.keySet());
        Collections.sort(sortedNames);

        for (String name : sortedNames) {
            Method m = methodMap.get(name);
            placement.put(m, methods.size());
            methods.add(m);
        }
    }
```

**Comment by pengdai** [comment]
Hi Guangmu,

Just mapping a method name to the method is insufficient because multiple methods can have the same method name but a different formal argument list. To support polymorphism, what's really needed here is to map a unique method signature to the method. We chose an integer index to a sorted method collection to represent the method signature. There may be other options, ranging from the full method string in the format of methodName(ArgType1, ...) to method UUID. But the integer index is simple and efficient in keeping with the overall spirits of this lightweight RMI implementation.

Cheers
Peng

**Comment by guangmuzhu** [comment]
HI Peng,

Thanks for your reply and I got what you said. Should the issue be closed?

**Comment by guangmuzhu** [comment]
Hi Peng,

Would you please tell me your e-mail address? I have some other questions about DSP, which the issue web page may not be a proper place to discuss about.

Regards
Guangmu
